Please add my contribution
csdojo-defaang/the-dojo-way pull request #102
Opened 2022-11-16 08:05 UTC by jivanbhardwaj

this is 2nd contribution to open source.

2022-11-16 18:32 UTC, ykdojo requested changes

2022-11-16 18:32 UTC, ykdojo commented on README.md
> +- [Jivan Bhardwaj](https://github.com/jivanbhardwaj)
can you put your name at the end?

2022-11-17 03:06 UTC, jivanbhardwaj commented
Okay .. I'll do that .

On Thu, 17 Nov, 2022, 12:02 am YK, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/csdojo-defaang/the-dojo-way/pull/102#discussion_r1024368464>
> :
>
> > @@ -54,6 +54,7 @@ Join us [here](https://discord.com/invite/nNtVfKddDD).
>  - [Shawn Charles](https://twitter.com/ShawnBasquiat)
>  - [Benny Yen](https://twitter.com/benny123tw/)
>  - [Rupali Haldiya](https://twitter.com/rupali_codes)
> +- [Jivan Bhardwaj](https://github.com/jivanbhardwaj)
>
> can you put your name at the end?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/csdojo-defaang/the-dojo-way/pull/102#pullrequestreview-1183130856>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOM46SFESUNYD5IIY3PQJY3WIUSDVANCNFSM6AAAAAASB5UDDY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-17 05:17 UTC, ykdojo requested changes

2022-11-17 05:17 UTC, ykdojo commented on README.md
> +i- [Muhammad Adnan Yousaf](https://twitter.com/ma593y)
please fix this line

2022-11-17 06:01 UTC, jivanbhardwaj commented on README.md
> +i- [Muhammad Adnan Yousaf](https://twitter.com/ma593y)
Done!

2022-11-17 10:07 UTC, subhoghoshX approved these changes

2022-11-17 10:07 UTC, merged

2022-11-17 10:29 UTC, jivanbhardwaj commented
Thanks, @subhoghoshX @ykdojo finally get good about open source contribution.

2022-11-17 16:47 UTC, subhoghoshX commented
> Thanks, @subhoghoshX @ykdojo finally get good about open source contribution.

Best wishes on your Opensource adventure.